image: Visual Studio 2019

version: 1.0.{build}.0

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\AndroCtrl.Protocols.AndroidDebugBridge
  - cmd: dotnet restore
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\AndroCtrl.Protocols.AndroidDebugBridge.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet test AndroCtrl.Protocols.AndroidDebugBridge.Tests.csproj --filter "TestCategory!=IntegrationTest & TestCategory!=PerformanceTest" "--logger:trx;LogFileName=testresults.trx" /p:CollectCoverage=true
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'

artifacts:
  - path: AndroCtrl.Protocols.AndroidDebugBridge\bin\Release\AndroCtrl.Protocols.AndroidDebugBridge.*.nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: oy2cfozgvkc2ovlnewca7dijuo33qvqetiokfobh5uespy
  skip_symbols: true
