image: Visual Studio 2022

version: 1.0.{build}

branches:
  only:
  - master
  - beta

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\AndroCtrl.Protocols.AndroidDebugBridge
  - cmd: dotnet restore
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\AndroCtrl.Protocols.AndroidDebugBridge.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet test AndroCtrl.Protocols.AndroidDebugBridge.Tests.csproj --filter "TestCategory!=IntegrationTest & TestCategory!=PerformanceTest" "--logger:trx;LogFileName=testresults.trx" /p:CollectCoverage=true
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'

artifacts:
  - path: AndroCtrl.Protocols.AndroidDebugBridge\bin\Release\AndroCtrl.Protocols.AndroidDebugBridge.*.nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: 2JgiRhKTzQyXmzR9JYLL6f9aNfxEKvr0pF0NxqQ1YY59O1Z5xQqI9kmDgFEiJe4y
  skip_symbols: true
