image: Visual Studio 2022

version: 2.0.{build}

branches:
  only:
  - master

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\AndroCtrl.Adb
  - cmd: dotnet restore
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\AndroCtrl.Adb.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet test AndroCtrl.Adb.Tests.csproj --filter "TestCategory!=IntegrationTest & TestCategory!=PerformanceTest" "--logger:trx;LogFileName=testresults.trx" /p:CollectCoverage=true
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'

artifacts:
  - path: AndroCtrl.Adb\bin\Release\AndroCtrl.Adb.*.*nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: 2JgiRhKTzQyXmzR9JYLL6f9aNfxEKvr0pF0NxqQ1YY59O1Z5xQqI9kmDgFEiJe4y
  skip_symbols: false
